version: 2.1
jobs:
  build:
    working_directory: ~/wdio-shadowdom-service
    docker:
      - image: cimg/node:16.14.0-browsers
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm ci
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: # lint
          name: lint
          command: npm run lint
      - run: # run tests
          name: test
          command: npm test
