name: Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        wdio-version: [ 6, 7, default ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      - run: chrome --version
      - run: /usr/bin/google-chrome --version
      - run: /usr/bin/chromium --version
      - run: /usr/bin/chromedriver --version
      - run: npm ci
      - run: |
          for pkg in webdriverio @wdio/cli @wdio/local-runner @wdio/mocha-framework @wdio/spec-reporter; do
            npm install "$pkg"@${{ matrix.wdio-version }} --save-dev ;
          done ;
        if: ${{ matrix.wdio-version != 'default' }}
        name: Install WebDriverIO
      - run: npx wdio --version
      - run: npm run lint
      - run: npm test
